// mac_llm_A.v
// Generated by: Claude Sonnet 4.6
// MAC unit -- multiply-accumulate with synchronous active-high reset

module mac (
    input  logic        clk,
    input  logic        rst,
    input  logic signed [7:0]  a,
    input  logic signed [7:0]  b,
    output logic signed [31:0] out
);

    always_ff @(posedge clk) begin
        if (rst)
            out <= 32'sd0;
        else
            out <= out + ({{16{a[7]}}, a} * {{16{b[7]}}, b});
    end

endmodule
