#!/usr/bin/env python3
"""
gen_fp4_lut.py -- FP4 E2M1 multiplication lookup table generator

FP4 E2M1 format:
  bit 3:   sign
  bit 2-1: exponent (2 bits, bias=1)
  bit 0:   mantissa (1 bit)

Representable values:
  Positive: 0.0, 0.5, 1.0, 1.5, 2.0, 3.0, 4.0, 6.0
  Negative: -0.0, -0.5, -1.0, -1.5, -2.0, -3.0, -4.0, -6.0

This script:
  1. Decodes all 16 FP4 values
  2. Computes all 256 products a x b as FP32
  3. Encodes each FP32 product as a 32-bit hex value
  4. Generates a SystemVerilog ROM for fp4_mul.sv
  5. Generates a Python verification table for testbench use

Author: Vamsidhar Reddy Eraganeni
Course: ECE 510 Spring 2026, Portland State University
"""

import struct
import numpy as np

# ---------------------------------------------------------------------------
# FP4 E2M1 decode
# bit 3: sign, bit 2-1: exponent (bias=1), bit 0: mantissa
# ---------------------------------------------------------------------------
def fp4_to_float(fp4):
    """Decode a 4-bit FP4 E2M1 value to Python float."""
    sign = (fp4 >> 3) & 0x1
    exp  = (fp4 >> 1) & 0x3
    mant = (fp4 >> 0) & 0x1

    if exp == 0:
        # subnormal: value = (-1)^sign x 2^(1-bias) x 0.mant
        # bias=1, so 2^(1-1) = 2^0 = 1
        value = (0.5 * mant)  # 2^0 x 0.mant = 0.mant
    else:
        # normal: value = (-1)^sign x 2^(exp-bias) x 1.mant
        value = (2 ** (exp - 1)) * (1.0 + 0.5 * mant)

    if sign:
        value = -value

    return value

# ---------------------------------------------------------------------------
# FP32 encode: float -> IEEE 754 32-bit integer
# ---------------------------------------------------------------------------
def float_to_fp32_bits(f):
    """Encode a Python float as IEEE 754 FP32 bit pattern (uint32)."""
    packed = struct.pack('>f', float(f))
    return struct.unpack('>I', packed)[0]

# ---------------------------------------------------------------------------
# Generate all 16 FP4 values
# ---------------------------------------------------------------------------
fp4_values = {}
print("FP4 E2M1 value table:")
print(f"{'Index':>6} {'Binary':>6} {'Float':>8}")
print("-" * 25)
for i in range(16):
    v = fp4_to_float(i)
    fp4_values[i] = v
    print(f"  {i:4d}   {i:04b}   {v:8.4f}")

print()

# ---------------------------------------------------------------------------
# Compute all 256 products
# ---------------------------------------------------------------------------
lut = {}
print("Computing 256 FP4 x FP4 products...")
for a in range(16):
    for b in range(16):
        product = fp4_values[a] * fp4_values[b]
        bits    = float_to_fp32_bits(product)
        lut[(a, b)] = (product, bits)

# ---------------------------------------------------------------------------
# Verify key products
# ---------------------------------------------------------------------------
print("\nVerification of key products:")
test_cases = [
    (0b0010, 0b0010, 1.0 * 1.0),   # 1.0 x 1.0 = 1.0
    (0b0100, 0b0010, 2.0 * 1.0),   # 2.0 x 1.0 = 2.0
    (0b0110, 0b0110, 4.0 * 4.0),   # 4.0 x 4.0 = 16.0
    (0b0111, 0b0111, 6.0 * 6.0),   # 6.0 x 6.0 = 36.0
    (0b1010, 0b0010, -1.0 * 1.0),  # -1.0 x 1.0 = -1.0
    (0b1010, 0b1010, -1.0 * -1.0), # -1.0 x -1.0 = 1.0
    (0b0000, 0b0111, 0.0 * 6.0),   # 0.0 x 6.0 = 0.0
]
all_pass = True
for a, b, expected in test_cases:
    got, bits = lut[(a, b)]
    ok = abs(got - expected) < 1e-6
    if not ok:
        all_pass = False
    print(f"  FP4[{a:04b}]({fp4_values[a]:5.1f}) x "
          f"FP4[{b:04b}]({fp4_values[b]:5.1f}) = "
          f"{got:8.4f} (expected {expected:8.4f}) "
          f"{'PASS' if ok else 'FAIL'}")

print(f"\nAll verification tests: {'PASS' if all_pass else 'FAIL'}")

# ---------------------------------------------------------------------------
# Generate SystemVerilog ROM
# ---------------------------------------------------------------------------
sv_lines = []
sv_lines.append('/*')
sv_lines.append(' * fp4_mul_lut.sv -- FP4 E2M1 multiplication LUT (auto-generated)')
sv_lines.append(' *')
sv_lines.append(' * Input:  a[3:0] FP4 E2M1, b[3:0] FP4 E2M1')
sv_lines.append(' * Output: result[31:0] FP32 IEEE 754 product')
sv_lines.append(' *')
sv_lines.append(' * Generated by gen_fp4_lut.py')
sv_lines.append(' * Author: Vamsidhar Reddy Eraganeni')
sv_lines.append(' * Course: ECE 510 Spring 2026, Portland State University')
sv_lines.append(' */')
sv_lines.append('')
sv_lines.append('module fp4_mul_lut (')
sv_lines.append('    input  logic [3:0]  a,')
sv_lines.append('    input  logic [3:0]  b,')
sv_lines.append('    output logic [31:0] result')
sv_lines.append(');')
sv_lines.append('')
sv_lines.append('    // 256-entry ROM: index = {a[3:0], b[3:0]}')
sv_lines.append('    // Each entry is the FP32 IEEE 754 encoding of a*b')
sv_lines.append('    logic [31:0] lut [0:255];')
sv_lines.append('')
sv_lines.append('    always_comb begin')
sv_lines.append('        case ({a, b})')

for a in range(16):
    for b in range(16):
        product, bits = lut[(a, b)]
        idx = (a << 4) | b
        sv_lines.append(f'            8\'h{idx:02X}: result = 32\'h{bits:08X};'
                        f'  // {fp4_values[a]:5.1f} x {fp4_values[b]:5.1f}'
                        f' = {product:8.4f}')

sv_lines.append('            default: result = 32\'h00000000;')
sv_lines.append('        endcase')
sv_lines.append('    end')
sv_lines.append('')
sv_lines.append('endmodule')

sv_content = '\n'.join(sv_lines)

with open('../rtl/fp4_mul_lut.sv', 'w') as f:
    f.write(sv_content)

print(f"\nGenerated fp4_mul_lut.sv with 256 LUT entries")

# ---------------------------------------------------------------------------
# Generate Python verification table for testbench
# ---------------------------------------------------------------------------
py_lines = []
py_lines.append('# fp4_lut_ref.py -- FP4 E2M1 LUT reference table')
py_lines.append('# Generated by gen_fp4_lut.py')
py_lines.append('# Use this to verify fp4_mul_lut.sv in testbench')
py_lines.append('')
py_lines.append('FP4_VALUES = {')
for i in range(16):
    py_lines.append(f'    0b{i:04b}: {fp4_values[i]},  # index {i}')
py_lines.append('}')
py_lines.append('')
py_lines.append('# LUT[(a,b)] = (float_product, fp32_bits)')
py_lines.append('FP4_LUT = {')
for a in range(16):
    for b in range(16):
        product, bits = lut[(a, b)]
        py_lines.append(f'    (0b{a:04b}, 0b{b:04b}): ({product}, 0x{bits:08X}),')
py_lines.append('}')

py_content = '\n'.join(py_lines)

with open('./fp4_lut_ref.py', 'w') as f:
    f.write(py_content)

print("Generated fp4_lut_ref.py for testbench verification")
print("\nDone. Files generated:")
print("  fp4_mul_lut.sv  -- SystemVerilog ROM (copy to project/upgrade/rtl/)")
print("  fp4_lut_ref.py  -- Python reference table (copy to project/upgrade/scripts/)")
