#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Vamsidhar Reddy Eraganeni
"""Emit one complete protocol-version-5 command as hex beats for gate-level power.

The C++ integration testbench already proves numerical correctness. This only
has to produce representative switching activity, so it writes the packet
stream for one command and the expected output beat count, and leaves score
checking to the existing suites.
"""
from __future__ import annotations

import argparse
import struct
import sys
from pathlib import Path

import numpy as np

MAGNITUDES = (0.0, 0.5, 1.0, 1.5, 2.0, 3.0, 4.0, 6.0)


def fp32_bits(value: float) -> int:
    return struct.unpack("<I", struct.pack("<f", np.float32(value)))[0]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--seq", type=int, default=8, help="sequence length T")
    parser.add_argument("--depth", type=int, default=64)
    parser.add_argument("--tile", type=int, default=4)
    parser.add_argument("--block-size", type=int, default=16)
    parser.add_argument("--seed", type=int, default=510)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()

    rng = np.random.default_rng(args.seed)
    blocks = -(-args.depth // args.block_size)
    tiles = -(-args.seq // args.tile)

    # FP4 codes, one nibble each, and positive FP32 block scales.
    q_codes = rng.integers(0, 16, (args.seq, args.depth), dtype=np.uint8)
    k_codes = rng.integers(0, 16, (args.seq, args.depth), dtype=np.uint8)
    q_scales = rng.choice([0.5, 1.0, 2.0], size=(args.seq, blocks))
    k_scales = rng.choice([0.5, 1.0, 2.0], size=(args.seq, blocks))

    beats: list[tuple[int, int]] = []  # (data, tlast)

    def add_scale_packet() -> None:
        values = [fp32_bits(q_scales[row][b]) for row in range(args.seq)
                  for b in range(blocks)]
        values += [fp32_bits(k_scales[row][b]) for row in range(args.seq)
                   for b in range(blocks)]
        # Two FP32 values per 64-bit beat, earliest in the low half.
        count = len(values) // 2
        for index in range(count):
            low, high = values[2 * index], values[2 * index + 1]
            beats.append(((high << 32) | low, index == count - 1))

    def add_tile_packet(codes: np.ndarray, base_row: int) -> None:
        flat = []
        for row in range(args.tile):
            source = base_row + row
            for column in range(args.depth):
                flat.append(int(codes[source][column]) if source < args.seq else 0)
        per_beat = 16
        total = -(-len(flat) // per_beat)
        for index in range(total):
            word = 0
            for lane in range(per_beat):
                position = index * per_beat + lane
                if position < len(flat):
                    word |= flat[position] << (4 * lane)
            beats.append((word, index == total - 1))

    add_scale_packet()
    # Protocol version 5: Q tile row, then every K tile column for that row.
    for q_tile in range(tiles):
        add_tile_packet(q_codes, q_tile * args.tile)
        for k_tile in range(tiles):
            add_tile_packet(k_codes, k_tile * args.tile)

    scores = args.seq * args.seq
    output_beats = sum(
        -(-(min(args.tile, args.seq - r * args.tile)
            * min(args.tile, args.seq - c * args.tile)) // 2)
        for r in range(tiles) for c in range(tiles)
    )
    lines = [f"// Generated by scripts/gen_gate_stimulus.py, seed {args.seed}",
             f"// T={args.seq} D_HEAD={args.depth} TILE={args.tile} "
             f"Bs={args.block_size}: {len(beats)} input beats, "
             f"{output_beats} output beats, {scores} scores",
             f"localparam int STIM_BEATS = {len(beats)};",
             f"localparam int STIM_OUTPUT_BEATS = {output_beats};",
             f"localparam int STIM_SEQ = {args.seq};"]
    lines.append(f"logic [63:0] stim_data [0:{len(beats) - 1}];")
    lines.append(f"logic stim_last [0:{len(beats) - 1}];")
    lines.append("initial begin")
    for index, (data, last) in enumerate(beats):
        lines.append(f"    stim_data[{index}] = 64'h{data:016x};"
                     f" stim_last[{index}] = 1'b{int(last)};")
    lines.append("end")
    args.out.write_text("\n".join(lines) + "\n")
    print(f"{len(beats)} input beats, {output_beats} output beats -> {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
